/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// InviteUserRequest
    /// </summary>
    [DataContract(Name = "InviteUser_request")]
    public partial class InviteUserRequest : IEquatable<InviteUserRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteUserRequest" /> class.
        /// </summary>
        /// <param name="inviteeId">ID of the user to invite.</param>
        /// <param name="userId">ID of the user in the party creating the invite. If using auth, this must match the user_id in the auth token.</param>
        public InviteUserRequest(string inviteeId = default(string), string userId = default(string))
        {
            this.InviteeId = inviteeId;
            this.UserId = userId;
        }

        /// <summary>
        /// ID of the user to invite
        /// </summary>
        /// <value>ID of the user to invite</value>
        [DataMember(Name = "invitee_id", EmitDefaultValue = false)]
        public string InviteeId { get; set; }

        /// <summary>
        /// ID of the user in the party creating the invite. If using auth, this must match the user_id in the auth token
        /// </summary>
        /// <value>ID of the user in the party creating the invite. If using auth, this must match the user_id in the auth token</value>
        [DataMember(Name = "user_id", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InviteUserRequest {\n");
            sb.Append("  InviteeId: ").Append(InviteeId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InviteUserRequest);
        }

        /// <summary>
        /// Returns true if InviteUserRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of InviteUserRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InviteUserRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.InviteeId == input.InviteeId ||
                    (this.InviteeId != null &&
                    this.InviteeId.Equals(input.InviteeId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InviteeId != null)
                {
                    hashCode = (hashCode * 59) + this.InviteeId.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
