/*
 * cjdevents
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: cjdevents: v3 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// MatchmakingServiceAcceptMatchBody
    /// </summary>
    [DataContract(Name = "MatchmakingServiceAcceptMatchBody")]
    public partial class MatchmakingServiceAcceptMatchBody : IEquatable<MatchmakingServiceAcceptMatchBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchmakingServiceAcceptMatchBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchmakingServiceAcceptMatchBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchmakingServiceAcceptMatchBody" /> class.
        /// </summary>
        /// <param name="accept">Boolean indicating if the user accepts the match (required).</param>
        public MatchmakingServiceAcceptMatchBody(bool accept = default(bool))
        {
            this.Accept = accept;
        }

        /// <summary>
        /// Boolean indicating if the user accepts the match
        /// </summary>
        /// <value>Boolean indicating if the user accepts the match</value>
        [DataMember(Name = "accept", IsRequired = true, EmitDefaultValue = true)]
        public bool Accept { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchmakingServiceAcceptMatchBody {\n");
            sb.Append("  Accept: ").Append(Accept).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MatchmakingServiceAcceptMatchBody);
        }

        /// <summary>
        /// Returns true if MatchmakingServiceAcceptMatchBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MatchmakingServiceAcceptMatchBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatchmakingServiceAcceptMatchBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Accept == input.Accept ||
                    this.Accept.Equals(input.Accept)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Accept.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
