/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// MatchmakingTicket
    /// </summary>
    [DataContract(Name = "matchmakingTicket")]
    public partial class MatchmakingTicket : IEquatable<MatchmakingTicket>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchmakingTicket" /> class.
        /// </summary>
        /// <param name="assignment">assignment.</param>
        /// <param name="createdAt">The time when the Ticket was created..</param>
        /// <param name="extensions">extensions.</param>
        /// <param name="firstMatchedAt">The time when the Ticket was first matched..</param>
        /// <param name="id">The ID of the ticket..</param>
        /// <param name="partyId">The id of the party that the user is in..</param>
        /// <param name="searchFields">searchFields.</param>
        /// <param name="userId">The ID of the user that created the ticket..</param>
        public MatchmakingTicket(MatchmakingAssignment assignment = default(MatchmakingAssignment), string createdAt = default(string), Dictionary<string, ProtobufAny> extensions = default(Dictionary<string, ProtobufAny>), string firstMatchedAt = default(string), string id = default(string), string partyId = default(string), MatchmakingSearchFields searchFields = default(MatchmakingSearchFields), string userId = default(string))
        {
            this.Assignment = assignment;
            this.CreatedAt = createdAt;
            this.Extensions = extensions;
            this.FirstMatchedAt = firstMatchedAt;
            this.Id = id;
            this.PartyId = partyId;
            this.SearchFields = searchFields;
            this.UserId = userId;
        }

        /// <summary>
        /// Gets or Sets Assignment
        /// </summary>
        [DataMember(Name = "assignment", EmitDefaultValue = false)]
        public MatchmakingAssignment Assignment { get; set; }

        /// <summary>
        /// The time when the Ticket was created.
        /// </summary>
        /// <value>The time when the Ticket was created.</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Extensions
        /// </summary>
        [DataMember(Name = "extensions", EmitDefaultValue = false)]
        public Dictionary<string, ProtobufAny> Extensions { get; set; }

        /// <summary>
        /// The time when the Ticket was first matched.
        /// </summary>
        /// <value>The time when the Ticket was first matched.</value>
        [DataMember(Name = "first_matched_at", EmitDefaultValue = false)]
        public string FirstMatchedAt { get; set; }

        /// <summary>
        /// The ID of the ticket.
        /// </summary>
        /// <value>The ID of the ticket.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The id of the party that the user is in.
        /// </summary>
        /// <value>The id of the party that the user is in.</value>
        [DataMember(Name = "party_id", EmitDefaultValue = false)]
        public string PartyId { get; set; }

        /// <summary>
        /// Gets or Sets SearchFields
        /// </summary>
        [DataMember(Name = "search_fields", EmitDefaultValue = false)]
        public MatchmakingSearchFields SearchFields { get; set; }

        /// <summary>
        /// The ID of the user that created the ticket.
        /// </summary>
        /// <value>The ID of the user that created the ticket.</value>
        [DataMember(Name = "user_id", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchmakingTicket {\n");
            sb.Append("  Assignment: ").Append(Assignment).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("  FirstMatchedAt: ").Append(FirstMatchedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PartyId: ").Append(PartyId).Append("\n");
            sb.Append("  SearchFields: ").Append(SearchFields).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MatchmakingTicket);
        }

        /// <summary>
        /// Returns true if MatchmakingTicket instances are equal
        /// </summary>
        /// <param name="input">Instance of MatchmakingTicket to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatchmakingTicket input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Assignment == input.Assignment ||
                    (this.Assignment != null &&
                    this.Assignment.Equals(input.Assignment))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.Extensions == input.Extensions ||
                    this.Extensions != null &&
                    input.Extensions != null &&
                    this.Extensions.SequenceEqual(input.Extensions)
                ) && 
                (
                    this.FirstMatchedAt == input.FirstMatchedAt ||
                    (this.FirstMatchedAt != null &&
                    this.FirstMatchedAt.Equals(input.FirstMatchedAt))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PartyId == input.PartyId ||
                    (this.PartyId != null &&
                    this.PartyId.Equals(input.PartyId))
                ) && 
                (
                    this.SearchFields == input.SearchFields ||
                    (this.SearchFields != null &&
                    this.SearchFields.Equals(input.SearchFields))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Assignment != null)
                {
                    hashCode = (hashCode * 59) + this.Assignment.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.Extensions != null)
                {
                    hashCode = (hashCode * 59) + this.Extensions.GetHashCode();
                }
                if (this.FirstMatchedAt != null)
                {
                    hashCode = (hashCode * 59) + this.FirstMatchedAt.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.PartyId != null)
                {
                    hashCode = (hashCode * 59) + this.PartyId.GetHashCode();
                }
                if (this.SearchFields != null)
                {
                    hashCode = (hashCode * 59) + this.SearchFields.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
