/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// Defines partiesRequestStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PartiesRequestStatus
    {
        /// <summary>
        /// Enum UNKNOWN for value: REQUEST_STATUS_UNKNOWN
        /// </summary>
        [EnumMember(Value = "REQUEST_STATUS_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum PENDING for value: REQUEST_STATUS_PENDING
        /// </summary>
        [EnumMember(Value = "REQUEST_STATUS_PENDING")]
        PENDING = 2,

        /// <summary>
        /// Enum ACCEPTED for value: REQUEST_STATUS_ACCEPTED
        /// </summary>
        [EnumMember(Value = "REQUEST_STATUS_ACCEPTED")]
        ACCEPTED = 3,

        /// <summary>
        /// Enum DECLINED for value: REQUEST_STATUS_DECLINED
        /// </summary>
        [EnumMember(Value = "REQUEST_STATUS_DECLINED")]
        DECLINED = 4
    }

}
