/*
 * cjdevents
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: cjdevents: v3 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// PartyVisibility represents the visibility level of a party.   - PARTY_VISIBILITY_UNKNOWN: PARTY_VISIBILITY_UNKNOWN indicates an unknown visibility.  - PARTY_VISIBILITY_PUBLIC: PARTY_VISIBILITY_PUBLIC indicates the party is visible to everyone.  - PARTY_VISIBILITY_PRIVATE: PARTY_VISIBILITY_PRIVATE indicates the party is private.  - PARTY_VISIBILITY_INVITE_ONLY: PARTY_VISIBILITY_INVITE_ONLY indicates the party is visible by invite only.  - PARTY_VISIBILITY_FRIENDS_ONLY: PARTY_VISIBILITY_FRIENDS_ONLY indicates the party is only visible to friends.
    /// </summary>
    /// <value>PartyVisibility represents the visibility level of a party.   - PARTY_VISIBILITY_UNKNOWN: PARTY_VISIBILITY_UNKNOWN indicates an unknown visibility.  - PARTY_VISIBILITY_PUBLIC: PARTY_VISIBILITY_PUBLIC indicates the party is visible to everyone.  - PARTY_VISIBILITY_PRIVATE: PARTY_VISIBILITY_PRIVATE indicates the party is private.  - PARTY_VISIBILITY_INVITE_ONLY: PARTY_VISIBILITY_INVITE_ONLY indicates the party is visible by invite only.  - PARTY_VISIBILITY_FRIENDS_ONLY: PARTY_VISIBILITY_FRIENDS_ONLY indicates the party is only visible to friends.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PartiesPartyVisibility
    {
        /// <summary>
        /// Enum UNKNOWN for value: PARTY_VISIBILITY_UNKNOWN
        /// </summary>
        [EnumMember(Value = "PARTY_VISIBILITY_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum PUBLIC for value: PARTY_VISIBILITY_PUBLIC
        /// </summary>
        [EnumMember(Value = "PARTY_VISIBILITY_PUBLIC")]
        PUBLIC = 2,

        /// <summary>
        /// Enum PRIVATE for value: PARTY_VISIBILITY_PRIVATE
        /// </summary>
        [EnumMember(Value = "PARTY_VISIBILITY_PRIVATE")]
        PRIVATE = 3,

        /// <summary>
        /// Enum INVITEONLY for value: PARTY_VISIBILITY_INVITE_ONLY
        /// </summary>
        [EnumMember(Value = "PARTY_VISIBILITY_INVITE_ONLY")]
        INVITEONLY = 4,

        /// <summary>
        /// Enum FRIENDSONLY for value: PARTY_VISIBILITY_FRIENDS_ONLY
        /// </summary>
        [EnumMember(Value = "PARTY_VISIBILITY_FRIENDS_ONLY")]
        FRIENDSONLY = 5
    }

}
