/*
 * cjdevents
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: cjdevents: v3 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// PartiesInviteUserResponse
    /// </summary>
    [DataContract(Name = "partiesInviteUserResponse")]
    public partial class PartiesInviteUserResponse : IEquatable<PartiesInviteUserResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartiesInviteUserResponse" /> class.
        /// </summary>
        /// <param name="invite">invite.</param>
        /// <param name="success">success.</param>
        public PartiesInviteUserResponse(PartiesRequest invite = default(PartiesRequest), bool success = default(bool))
        {
            this.Invite = invite;
            this.Success = success;
        }

        /// <summary>
        /// Gets or Sets Invite
        /// </summary>
        [DataMember(Name = "invite", EmitDefaultValue = false)]
        public PartiesRequest Invite { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartiesInviteUserResponse {\n");
            sb.Append("  Invite: ").Append(Invite).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PartiesInviteUserResponse);
        }

        /// <summary>
        /// Returns true if PartiesInviteUserResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PartiesInviteUserResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartiesInviteUserResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Invite == input.Invite ||
                    (this.Invite != null &&
                    this.Invite.Equals(input.Invite))
                ) && 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Invite != null)
                {
                    hashCode = (hashCode * 59) + this.Invite.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Success.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
