/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// PartiesListPartyInvitesResponse
    /// </summary>
    [DataContract(Name = "partiesListPartyInvitesResponse")]
    public partial class PartiesListPartyInvitesResponse : IEquatable<PartiesListPartyInvitesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartiesListPartyInvitesResponse" /> class.
        /// </summary>
        /// <param name="invites">invites.</param>
        public PartiesListPartyInvitesResponse(List<PartiesRequest> invites = default(List<PartiesRequest>))
        {
            this.Invites = invites;
        }

        /// <summary>
        /// Gets or Sets Invites
        /// </summary>
        [DataMember(Name = "invites", EmitDefaultValue = false)]
        public List<PartiesRequest> Invites { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartiesListPartyInvitesResponse {\n");
            sb.Append("  Invites: ").Append(Invites).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PartiesListPartyInvitesResponse);
        }

        /// <summary>
        /// Returns true if PartiesListPartyInvitesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PartiesListPartyInvitesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartiesListPartyInvitesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Invites == input.Invites ||
                    this.Invites != null &&
                    input.Invites != null &&
                    this.Invites.SequenceEqual(input.Invites)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Invites != null)
                {
                    hashCode = (hashCode * 59) + this.Invites.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
