/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StorageBatchUpsertSubDocumentsRequest
    /// </summary>
    [DataContract(Name = "storageBatchUpsertSubDocumentsRequest")]
    public partial class StorageBatchUpsertSubDocumentsRequest : IEquatable<StorageBatchUpsertSubDocumentsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageBatchUpsertSubDocumentsRequest" /> class.
        /// </summary>
        /// <param name="subDocuments">subDocuments.</param>
        public StorageBatchUpsertSubDocumentsRequest(List<StorageUpsertSubDocumentRequest> subDocuments = default(List<StorageUpsertSubDocumentRequest>))
        {
            this.SubDocuments = subDocuments;
        }

        /// <summary>
        /// Gets or Sets SubDocuments
        /// </summary>
        [DataMember(Name = "sub_documents", EmitDefaultValue = false)]
        public List<StorageUpsertSubDocumentRequest> SubDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageBatchUpsertSubDocumentsRequest {\n");
            sb.Append("  SubDocuments: ").Append(SubDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageBatchUpsertSubDocumentsRequest);
        }

        /// <summary>
        /// Returns true if StorageBatchUpsertSubDocumentsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageBatchUpsertSubDocumentsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageBatchUpsertSubDocumentsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SubDocuments == input.SubDocuments ||
                    this.SubDocuments != null &&
                    input.SubDocuments != null &&
                    this.SubDocuments.SequenceEqual(input.SubDocuments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubDocuments != null)
                {
                    hashCode = (hashCode * 59) + this.SubDocuments.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
