/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// UpdatePartyPlayerMetadataRequest
    /// </summary>
    [DataContract(Name = "UpdatePartyPlayerMetadata_request")]
    public partial class UpdatePartyPlayerMetadataRequest : IEquatable<UpdatePartyPlayerMetadataRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePartyPlayerMetadataRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePartyPlayerMetadataRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePartyPlayerMetadataRequest" /> class.
        /// </summary>
        /// <param name="metadata">A Json document of metadata to be stored with the player (required).</param>
        public UpdatePartyPlayerMetadataRequest(Object metadata = default(Object))
        {
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for UpdatePartyPlayerMetadataRequest and cannot be null");
            }
            this.Metadata = metadata;
        }

        /// <summary>
        /// A Json document of metadata to be stored with the player
        /// </summary>
        /// <value>A Json document of metadata to be stored with the player</value>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePartyPlayerMetadataRequest {\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdatePartyPlayerMetadataRequest);
        }

        /// <summary>
        /// Returns true if UpdatePartyPlayerMetadataRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdatePartyPlayerMetadataRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatePartyPlayerMetadataRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Metadata != null)
                {
                    hashCode = (hashCode * 59) + this.Metadata.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
