// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_server_fleets_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameServerFleets {

  /// <summary>Holder for reflection information generated from game_server_fleets_types.proto</summary>
  public static partial class GameServerFleetsTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for game_server_fleets_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameServerFleetsTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5nYW1lX3NlcnZlcl9mbGVldHNfdHlwZXMucHJvdG8SEmdhbWVfc2VydmVy",
            "X2ZsZWV0cyJsChxVcGRhdGVHYW1lU2VydmVyU3RhdGVSZXF1ZXN0EhgKEGdh",
            "bWVfc2VydmVyX25hbWUYASABKAkSMgoFc3RhdGUYAiABKA4yIy5nYW1lX3Nl",
            "cnZlcl9mbGVldHMuR2FtZVNlcnZlclN0YXRlIjAKHVVwZGF0ZUdhbWVTZXJ2",
            "ZXJTdGF0ZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgihQIKG0V2ZW50R2Ft",
            "ZVNlcnZlclN0YXRlVXBkYXRlZBJBCgpldmVudF90eXBlGAEgASgOMi0uZ2Ft",
            "ZV9zZXJ2ZXJfZmxlZXRzLkdhbWVTZXJ2ZXJGbGVldHNFdmVudFR5cGUSGAoQ",
            "Z2FtZV9zZXJ2ZXJfbmFtZRgCIAEoCRI7Cg5wcmV2aW91c19zdGF0ZRgDIAEo",
            "DjIjLmdhbWVfc2VydmVyX2ZsZWV0cy5HYW1lU2VydmVyU3RhdGUSNgoJbmV3",
            "X3N0YXRlGAQgASgOMiMuZ2FtZV9zZXJ2ZXJfZmxlZXRzLkdhbWVTZXJ2ZXJT",
            "dGF0ZRIUCgxwdWJsaXNoZWRfYXQYBSABKAMqSwoPR2FtZVNlcnZlclN0YXRl",
            "EgsKB1VOS05PV04QABINCglBTExPQ0FURUQQARIJCgVSRUFEWRACEhEKDVNI",
            "VVRUSU5HX0RPV04QAypWChlHYW1lU2VydmVyRmxlZXRzRXZlbnRUeXBlEhYK",
            "ElVOS05PV05fRVZFTlRfVFlQRRAAEiEKHUdTRl9HQU1FX1NFUlZFUl9TVEFU",
            "RV9VUERBVEVEEAFCPVo7Z2l0aHViLmNvbS9zbmFwc2VyLWVuZ2luZS9zZXJ2",
            "aWNlcy9nYW1lLXNlcnZlci1mbGVldHMvcHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameServerFleets.GameServerState), typeof(global::GameServerFleets.GameServerFleetsEventType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameServerFleets.UpdateGameServerStateRequest), global::GameServerFleets.UpdateGameServerStateRequest.Parser, new[]{ "GameServerName", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameServerFleets.UpdateGameServerStateResponse), global::GameServerFleets.UpdateGameServerStateResponse.Parser, new[]{ "Success" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameServerFleets.EventGameServerStateUpdated), global::GameServerFleets.EventGameServerStateUpdated.Parser, new[]{ "EventType", "GameServerName", "PreviousState", "NewState", "PublishedAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameServerState {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ALLOCATED")] Allocated = 1,
    [pbr::OriginalName("READY")] Ready = 2,
    [pbr::OriginalName("SHUTTING_DOWN")] ShuttingDown = 3,
  }

  public enum GameServerFleetsEventType {
    [pbr::OriginalName("UNKNOWN_EVENT_TYPE")] UnknownEventType = 0,
    [pbr::OriginalName("GSF_GAME_SERVER_STATE_UPDATED")] GsfGameServerStateUpdated = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Requests and Responses 
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateGameServerStateRequest : pb::IMessage<UpdateGameServerStateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateGameServerStateRequest> _parser = new pb::MessageParser<UpdateGameServerStateRequest>(() => new UpdateGameServerStateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateGameServerStateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameServerFleets.GameServerFleetsTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateRequest(UpdateGameServerStateRequest other) : this() {
      gameServerName_ = other.gameServerName_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateRequest Clone() {
      return new UpdateGameServerStateRequest(this);
    }

    /// <summary>Field number for the "game_server_name" field.</summary>
    public const int GameServerNameFieldNumber = 1;
    private string gameServerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameServerName {
      get { return gameServerName_; }
      set {
        gameServerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 2;
    private global::GameServerFleets.GameServerState state_ = global::GameServerFleets.GameServerState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameServerFleets.GameServerState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateGameServerStateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateGameServerStateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameServerName != other.GameServerName) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameServerName.Length != 0) hash ^= GameServerName.GetHashCode();
      if (State != global::GameServerFleets.GameServerState.Unknown) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameServerName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameServerName);
      }
      if (State != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameServerName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameServerName);
      }
      if (State != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameServerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameServerName);
      }
      if (State != global::GameServerFleets.GameServerState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateGameServerStateRequest other) {
      if (other == null) {
        return;
      }
      if (other.GameServerName.Length != 0) {
        GameServerName = other.GameServerName;
      }
      if (other.State != global::GameServerFleets.GameServerState.Unknown) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GameServerName = input.ReadString();
            break;
          }
          case 16: {
            State = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GameServerName = input.ReadString();
            break;
          }
          case 16: {
            State = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateGameServerStateResponse : pb::IMessage<UpdateGameServerStateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateGameServerStateResponse> _parser = new pb::MessageParser<UpdateGameServerStateResponse>(() => new UpdateGameServerStateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateGameServerStateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameServerFleets.GameServerFleetsTypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateResponse(UpdateGameServerStateResponse other) : this() {
      success_ = other.success_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGameServerStateResponse Clone() {
      return new UpdateGameServerStateResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateGameServerStateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateGameServerStateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateGameServerStateResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventGameServerStateUpdated : pb::IMessage<EventGameServerStateUpdated>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventGameServerStateUpdated> _parser = new pb::MessageParser<EventGameServerStateUpdated>(() => new EventGameServerStateUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventGameServerStateUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameServerFleets.GameServerFleetsTypesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGameServerStateUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGameServerStateUpdated(EventGameServerStateUpdated other) : this() {
      eventType_ = other.eventType_;
      gameServerName_ = other.gameServerName_;
      previousState_ = other.previousState_;
      newState_ = other.newState_;
      publishedAt_ = other.publishedAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGameServerStateUpdated Clone() {
      return new EventGameServerStateUpdated(this);
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::GameServerFleets.GameServerFleetsEventType eventType_ = global::GameServerFleets.GameServerFleetsEventType.UnknownEventType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameServerFleets.GameServerFleetsEventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "game_server_name" field.</summary>
    public const int GameServerNameFieldNumber = 2;
    private string gameServerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameServerName {
      get { return gameServerName_; }
      set {
        gameServerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "previous_state" field.</summary>
    public const int PreviousStateFieldNumber = 3;
    private global::GameServerFleets.GameServerState previousState_ = global::GameServerFleets.GameServerState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameServerFleets.GameServerState PreviousState {
      get { return previousState_; }
      set {
        previousState_ = value;
      }
    }

    /// <summary>Field number for the "new_state" field.</summary>
    public const int NewStateFieldNumber = 4;
    private global::GameServerFleets.GameServerState newState_ = global::GameServerFleets.GameServerState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameServerFleets.GameServerState NewState {
      get { return newState_; }
      set {
        newState_ = value;
      }
    }

    /// <summary>Field number for the "published_at" field.</summary>
    public const int PublishedAtFieldNumber = 5;
    private long publishedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PublishedAt {
      get { return publishedAt_; }
      set {
        publishedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventGameServerStateUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventGameServerStateUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (GameServerName != other.GameServerName) return false;
      if (PreviousState != other.PreviousState) return false;
      if (NewState != other.NewState) return false;
      if (PublishedAt != other.PublishedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::GameServerFleets.GameServerFleetsEventType.UnknownEventType) hash ^= EventType.GetHashCode();
      if (GameServerName.Length != 0) hash ^= GameServerName.GetHashCode();
      if (PreviousState != global::GameServerFleets.GameServerState.Unknown) hash ^= PreviousState.GetHashCode();
      if (NewState != global::GameServerFleets.GameServerState.Unknown) hash ^= NewState.GetHashCode();
      if (PublishedAt != 0L) hash ^= PublishedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventType != global::GameServerFleets.GameServerFleetsEventType.UnknownEventType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (GameServerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GameServerName);
      }
      if (PreviousState != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PreviousState);
      }
      if (NewState != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) NewState);
      }
      if (PublishedAt != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PublishedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventType != global::GameServerFleets.GameServerFleetsEventType.UnknownEventType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (GameServerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GameServerName);
      }
      if (PreviousState != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PreviousState);
      }
      if (NewState != global::GameServerFleets.GameServerState.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) NewState);
      }
      if (PublishedAt != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PublishedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::GameServerFleets.GameServerFleetsEventType.UnknownEventType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (GameServerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameServerName);
      }
      if (PreviousState != global::GameServerFleets.GameServerState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PreviousState);
      }
      if (NewState != global::GameServerFleets.GameServerState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NewState);
      }
      if (PublishedAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PublishedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventGameServerStateUpdated other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::GameServerFleets.GameServerFleetsEventType.UnknownEventType) {
        EventType = other.EventType;
      }
      if (other.GameServerName.Length != 0) {
        GameServerName = other.GameServerName;
      }
      if (other.PreviousState != global::GameServerFleets.GameServerState.Unknown) {
        PreviousState = other.PreviousState;
      }
      if (other.NewState != global::GameServerFleets.GameServerState.Unknown) {
        NewState = other.NewState;
      }
      if (other.PublishedAt != 0L) {
        PublishedAt = other.PublishedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::GameServerFleets.GameServerFleetsEventType) input.ReadEnum();
            break;
          }
          case 18: {
            GameServerName = input.ReadString();
            break;
          }
          case 24: {
            PreviousState = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
          case 32: {
            NewState = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
          case 40: {
            PublishedAt = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventType = (global::GameServerFleets.GameServerFleetsEventType) input.ReadEnum();
            break;
          }
          case 18: {
            GameServerName = input.ReadString();
            break;
          }
          case 24: {
            PreviousState = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
          case 32: {
            NewState = (global::GameServerFleets.GameServerState) input.ReadEnum();
            break;
          }
          case 40: {
            PublishedAt = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
